[features]
seeds = true
skip-lint = false

[workspace]
members = ["programs/polyswarms"]

[programs.localnet]
polyswarms = "Polyswarms1111111111111111111111111111111111"

[programs.devnet]
polyswarms = "Polyswarms1111111111111111111111111111111111"

[programs.testnet]
polyswarms = "Polyswarms1111111111111111111111111111111111"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "testnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"
